language: node_js
node_js:
  - "8"
dist: trusty
services: 
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - npm run build
script:
  - nohup npm run start &
  # nohup: if shell is closed, dont kill anything this command creates
  # &: run command in subshell (in the background)
  - sleep 3
  # wait for 3 seconds
  - npm run test